import "./globals.css";
import "react-toastify/dist/ReactToastify.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import * as toast from "react-toastify";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <div className="relative z-[51]">
        <toast.ToastContainer
          stacked
          newestOnTop
          theme={"light"}
          autoClose={2500}
          draggablePercent={60}
          className=" z-[51]"
          transition={toast.Bounce}
          position="top-center"
          pauseOnHover={false}
        />
      </div>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
